### ISSUE TITLE
copy assignment

### ISSUE THREAD

**Issue by aaronhaslett** [Desetude/Hafos#2]
https://github.com/Desetude/EpOs/blob/595b8a09daf367ac0db2ea1ba509dd4b7b3ef62b/kernel/arch/i386/tables/gdt.c#L26
This is it, I think.  This line copies the struct then you're just editing that copy for the rest of the function.

**Comment by hfreeb** [comment]
Thanks! I think that was one of the issues. The main issue, I just found out is that my gdt_pointer struct didn't have `__attribute__((packed))`.
